using Pgvector;

namespace PatientAccess.Data.Models;

/// <summary>
/// Clinical terminology knowledge base with vector embedding for semantic search (DR-010, AIR-R04).
/// Stores clinical terms with 1536-dimensional embeddings generated by Azure OpenAI text-embedding-3-small.
/// Supports hybrid retrieval combining semantic similarity and keyword search across medical vocabulary.
/// </summary>
public class ClinicalTerminology
{
    /// <summary>
    /// Unique identifier for the clinical terminology entry.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Clinical term or phrase.
    /// Examples: "Type 2 Diabetes Mellitus", "Hypertension", "Asthma"
    /// </summary>
    public string Term { get; set; } = string.Empty;

    /// <summary>
    /// Terminology category classification.
    /// Values: "Diagnosis", "Medication", "Procedure", "Symptom", "Anatomy", "Lab Test"
    /// </summary>
    public string Category { get; set; } = string.Empty;

    /// <summary>
    /// Alternative terms and synonyms stored as JSONB array.
    /// Examples for "Type 2 Diabetes Mellitus": ["T2DM", "NIDDM", "Adult-onset diabetes"]
    /// </summary>
    public string Synonyms { get; set; } = "[]";

    /// <summary>
    /// 1536-dimensional vector embedding generated by Azure OpenAI text-embedding-3-small.
    /// Used for semantic similarity search with cosine distance.
    /// </summary>
    public Vector? Embedding { get; set; }

    /// <summary>
    /// Original text chunk used for embedding generation.
    /// Stored for audit trail and re-indexing purposes.
    /// </summary>
    public string ChunkText { get; set; } = string.Empty;

    /// <summary>
    /// JSONB metadata for additional contextual information.
    /// Contains: source, mappedICD10Codes, mappedCPTCodes, clinicalContext, definitions
    /// </summary>
    public string Metadata { get; set; } = "{}";

    /// <summary>
    /// Source terminology system.
    /// Examples: "SNOMED-CT", "LOINC", "RxNorm", "Internal"
    /// </summary>
    public string Source { get; set; } = string.Empty;

    /// <summary>
    /// Active status flag. False for deprecated terms.
    /// Enables soft delete pattern for terminology updates.
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// UTC timestamp of record creation.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// UTC timestamp of last update.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }
}
