using Pgvector;

namespace PatientAccess.Data.Models;

/// <summary>
/// CPT (Current Procedural Terminology) medical procedure code with vector embedding for semantic search (DR-010, AIR-R04).
/// Stores CPT codes with 1536-dimensional embeddings generated by Azure OpenAI text-embedding-3-small.
/// Supports hybrid retrieval combining semantic similarity and keyword search.
/// </summary>
public class CPTCode
{
    /// <summary>
    /// Unique identifier for the CPT code entry.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// CPT code value (e.g., "99213", "80053").
    /// Unique identifier within the CPT system.
    /// </summary>
    public string Code { get; set; } = string.Empty;

    /// <summary>
    /// Full CPT code description.
    /// Example: "Office or other outpatient visit for the evaluation and management of an established patient"
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// CPT category classification.
    /// Examples: "Evaluation and Management", "Laboratory Procedures"
    /// </summary>
    public string Category { get; set; } = string.Empty;

    /// <summary>
    /// Optional CPT modifier codes.
    /// Examples: "25" (Significant separately identifiable E/M service), "59" (Distinct procedural service)
    /// </summary>
    public string? Modifier { get; set; }

    /// <summary>
    /// 1536-dimensional vector embedding generated by Azure OpenAI text-embedding-3-small.
    /// Used for semantic similarity search with cosine distance.
    /// </summary>
    public Vector? Embedding { get; set; }

    /// <summary>
    /// Original text chunk used for embedding generation.
    /// Stored for audit trail and re-indexing purposes.
    /// </summary>
    public string ChunkText { get; set; } = string.Empty;

    /// <summary>
    /// JSONB metadata for additional contextual information.
    /// Contains: version, effectiveDate, status, rvuValue, billingGuidelines
    /// </summary>
    public string Metadata { get; set; } = "{}";

    /// <summary>
    /// CPT version identifier.
    /// Example: "CPT-2024"
    /// </summary>
    public string Version { get; set; } = string.Empty;

    /// <summary>
    /// Active status flag. False for deprecated codes.
    /// Enables soft delete pattern for code updates.
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// UTC timestamp of record creation.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// UTC timestamp of last update.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }
}
