using Pgvector;

namespace PatientAccess.Data.Models;

/// <summary>
/// ICD-10 medical diagnosis code with vector embedding for semantic search (DR-010, AIR-R04).
/// Stores ICD-10-CM codes with 1536-dimensional embeddings generated by Azure OpenAI text-embedding-3-small.
/// Supports hybrid retrieval combining semantic similarity and keyword search.
/// </summary>
public class ICD10Code
{
    /// <summary>
    /// Unique identifier for the ICD-10 code entry.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// ICD-10 code value (e.g., "E11.9", "E11.65").
    /// Unique identifier within the ICD-10 system.
    /// </summary>
    public string Code { get; set; } = string.Empty;

    /// <summary>
    /// Full ICD-10 code description.
    /// Example: "Type 2 diabetes mellitus without complications"
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// ICD-10 category classification.
    /// Example: "Endocrine, nutritional and metabolic diseases"
    /// </summary>
    public string Category { get; set; } = string.Empty;

    /// <summary>
    /// ICD-10 chapter code range.
    /// Example: "E00-E89" for endocrine diseases.
    /// </summary>
    public string ChapterCode { get; set; } = string.Empty;

    /// <summary>
    /// 1536-dimensional vector embedding generated by Azure OpenAI text-embedding-3-small.
    /// Used for semantic similarity search with cosine distance.
    /// </summary>
    public Vector? Embedding { get; set; }

    /// <summary>
    /// Original text chunk used for embedding generation.
    /// Stored for audit trail and re-indexing purposes.
    /// </summary>
    public string ChunkText { get; set; } = string.Empty;

    /// <summary>
    /// JSONB metadata for additional contextual information.
    /// Contains: version, effectiveDate, status, subcategories, relatedCodes
    /// </summary>
    public string Metadata { get; set; } = "{}";

    /// <summary>
    /// ICD-10 version identifier.
    /// Example: "ICD-10-CM-2024"
    /// </summary>
    public string Version { get; set; } = string.Empty;

    /// <summary>
    /// Active status flag. False for deprecated codes.
    /// Enables soft delete pattern for code updates.
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// UTC timestamp of record creation.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// UTC timestamp of last update.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }
}
