name: CD - Deploy Frontend via FTP

on:
  workflow_dispatch:

jobs:
  deploy:
    name: CD - Deploy to FTP
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: src/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_41457524
          password: PropelIq123
          port: 21
          local-dir: src/frontend/dist/
          server-dir: /htdocs/
